# Generated by Django 4.0 on 2022-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fichepatient_description_probleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepatient',
            name='type_kine',
            field=models.CharField(blank=True, choices=[('K', 'Kinésithérapie'), ('OS', 'Osthéopatie'), ('KR', 'Kinésithérapie Respiratoire'), ('P', 'Pédiatrie')], max_length=2),
        ),
    ]
