# Generated by Django 4.0 on 2022-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fichepatient_type_kine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepatient',
            name='adresse',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fichepatient',
            name='age',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichepatient',
            name='description_probleme',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
