# Generated by Django 4.0 on 2022-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(max_length=1024),
        ),
    ]
