# Generated by Django 4.0 on 2022-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rendezvous_date_alter_rendezvous_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_soin',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
