# Generated by Django 4.0 on 2022-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rendezvous_type_soin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='type_soin',
        ),
    ]
