# Generated by Django 4.0 on 2022-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_rendezvous_type_soin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type_soin',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
