# Generated by Django 4.0 on 2022-04-20 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_fichepatient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('heure', models.TimeField(default=datetime.datetime.now)),
                ('dest', models.CharField(max_length=32)),
                ('contenu', models.TextField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fichepatient')),
            ],
        ),
    ]
