# Generated by Django 4.0 on 2022-04-23 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_message_date_alter_message_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='heure',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
