# Generated by Django 4.0 on 2022-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_message_date_alter_message_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
            ],
        ),
    ]
