# Generated by Django 4.0 on 2022-04-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_videotuto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_detaillee', models.TextField(max_length=5096)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fichepatient')),
                ('videos', models.ManyToManyField(to='api.VideoTuto')),
            ],
        ),
    ]
