# Generated by Django 4.0 on 2022-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='titre_routine',
            field=models.CharField(default='routine', max_length=1024),
        ),
    ]
