# Generated by Django 4.0 on 2022-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_routine_titre_routine_alter_routine_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='videos',
            field=models.ManyToManyField(default=list, null=True, to='api.VideoTuto'),
        ),
    ]
