# Generated by Django 4.0 on 2022-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_routine_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='api.VideoTuto'),
        ),
    ]
