# Generated by Django 4.0 on 2022-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_fichepatient_autorisation_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepatient',
            name='autorisation_consultation',
            field=models.CharField(default='Non', max_length=3),
        ),
    ]
